name: Build iOS XCFrameworks (Xerces + libE57Format)

jobs:
  xerces-autotools-ios:
    runs-on: macos-14
    steps:
      - name: Checkout Xerces-C
        uses: actions/checkout@v4
        with:
          repository: apache/xerces-c
          ref: xerces-3.2.2

      - name: Install Autotools
        run: |
          brew install autoconf automake libtool

      - name: Bootstrap
        run: |
          ./reconf   # Xerces bringt ein Skript mit, ruft autoreconf -fvi auf

      - name: Configure for iOS Device (arm64)
        run: |
          mkdir build-device && cd build-device
          export CC="$(xcrun --sdk iphoneos --find clang)"
          export CXX="$(xcrun --sdk iphoneos --find clang++)"
          ../configure \
            --host=arm-apple-darwin \
            --disable-shared \
            --enable-static \
            --prefix=$PWD/install \
            CXXFLAGS="-arch arm64 -miphoneos-version-min=13.0" \
            CFLAGS="-arch arm64 -miphoneos-version-min=13.0"

      - name: Build Xerces Device
        run: |
          cd build-device
          make -j$(sysctl -n hw.ncpu)
          make install

      - name: Configure for iOS Simulator (arm64)
        run: |
          mkdir ../build-sim && cd ../build-sim
          export CC="$(xcrun --sdk iphonesimulator --find clang)"
          export CXX="$(xcrun --sdk iphonesimulator --find clang++)"
          ../configure \
            --host=arm-apple-darwin \
            --disable-shared \
            --enable-static \
            --prefix=$PWD/install \
            CXXFLAGS="-arch arm64 -mios-simulator-version-min=13.0" \
            CFLAGS="-arch arm64 -mios-simulator-version-min=13.0"

      - name: Build Xerces Simulator
        run: |
          cd build-sim
          make -j$(sysctl -n hw.ncpu)
          make install

      - name: Create XCFramework
        run: |
          mkdir -p xcframework
          xcodebuild -create-xcframework \
            -library build-device/src/.libs/libxerces-c.a -headers build-device/install/include \
            -library build-sim/src/.libs/libxerces-c.a    -headers build-sim/install/include \
            -output xcframework/XercesC.xcframework

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: XercesC-iOS
          path: xcframework/XercesC.xcframework
